import Head from 'next/head'
import Demo from '../components/Demo'

export default function Contact() {


  const messages = ["ok", "super", "j'adore"]

  return(
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Contact
        </h1>
        { messages.map((m, i) => (
          <Demo key={i} message={m} />
        ))}
      </main>

    </>

  )







}